apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
        - name: devsecops
          image: delio/devsecop-js:1.0.0
          ports:
            - containerPort: 9000
      serviceAccountName: devops-secret
      volumes:
      - name: devsops-auth
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: “nodejs-deployment-aws-secrets"
      containers:
      - name: devsecops
        image: delio/devsecop-js:1.0.0
        ports:
        - containerPort: 9000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
            name: db-credentials
            key:  api-key 
        volumeMounts:
        - name: devsops-auth
          mountPath: "/mnt/secrets-store"
          readOnly: true
